# Real-world patient symptom language database
PATIENT_SYMPTOM_KEYWORDS = [
    # CARDIAC CONDITIONS - Patient language (what they ACTUALLY say)
    ("chest pain", "Myocardial infarction/Coronary artery disease"),
    ("my chest hurts", "Myocardial infarction/Coronary artery disease"),
    ("chest tightness", "Myocardial infarction/Coronary artery disease"),
    ("chest pressure", "Myocardial infarction/Coronary artery disease"),
    ("feel pressure", "Myocardial infarction/Coronary artery disease"),
    ("crushing", "Myocardial infarction"),
    ("elephant on chest", "Myocardial infarction"),
    ("heart attack", "Myocardial infarction"),
    ("acute coronary", "Acute coronary syndrome"),
    ("heart pounding", "Cardiac arrhythmia"),
    ("heart racing", "Cardiac palpitations/Arrhythmia"),
    ("heart beating weird", "Cardiac arrhythmia"),
    ("heart flutter", "Cardiac arrhythmia"),
    ("palpitations", "Cardiac palpitations/Arrhythmia"),
    ("heart failure", "Heart failure"),
    ("high blood pressure", "Hypertension"),
    ("blood pressure", "Hypertension"),
    # RESPIRATORY CONDITIONS - Patient language
    ("can't breathe", "Dyspnea/Asthma/COPD"),
    ("can't catch my breath", "Dyspnea/Asthma"),
    ("catch my breath", "Dyspnea/Asthma"),
    ("shortness of breath", "Dyspnea/Asthma/COPD"),
    ("short of breath", "Dyspnea/Asthma/COPD"),
    ("trouble breathing", "Dyspnea/Asthma"),
    ("difficulty breathing", "Dyspnea/Asthma"),
    ("i'm wheezing", "Asthma/COPD"),
    ("wheezing", "Asthma/COPD"),
    ("tight chest", "Asthma/COPD"),
    ("coughing up blood", "Tuberculosis/Pneumonia/Lung cancer"),
    ("blood in my sputum", "Tuberculosis/Pneumonia"),
    ("blood in cough", "Tuberculosis/Pneumonia"),
    ("persistent cough", "Pneumonia/Bronchitis/Tuberculosis"),
    ("hacking cough", "Bronchitis/Pneumonia"),
    ("won't stop coughing", "Bronchitis/Pneumonia"),
    ("constant cough", "Bronchitis/Pneumonia/TB"),
    ("cough for weeks", "Tuberculosis/Bronchitis"),
    ("fever and cough", "Pneumonia/Bronchitis"),
    ("cough with fever", "Pneumonia/Bronchitis"),
    ("cough", "Common cold/Bronchitis"),
    ("chest congestion", "Bronchitis/Pneumonia"),
    ("congested", "Common cold/Bronchitis"),
    ("stuffy", "Common cold/Sinusitis"),
    ("runny nose", "Common cold/Sinusitis"),
    ("sore throat", "Pharyngitis/Common cold"),
    # NEUROLOGICAL CONDITIONS - Patient language
    ("bad headache", "Migraine/Tension headache"),
    ("worst headache", "Meningitis/Subarachnoid hemorrhage"),
    ("worst of my life", "Meningitis"),
    ("head is killing me", "Migraine/Headache"),
    ("severe headache", "Migraine/Tension headache"),
    ("migraine", "Migraine headache"),
    ("pounding headache", "Migraine"),
    ("throbbing", "Migraine"),
    ("neck stiff", "Meningitis/Cervical strain"),
    ("stiff neck", "Meningitis"),
    ("can't turn my head", "Meningitis/Cervical strain"),
    ("high fever headache", "Meningitis"),
    ("sensitivity to light", "Meningitis/Migraine"),
    ("light hurts", "Meningitis/Migraine"),
    ("hurts to look at light", "Meningitis/Migraine"),
    ("dizzy", "Vertigo/Neurological disorder"),
    ("dizziness", "Vertigo/Neurological disorder"),
    ("room spinning", "Vertigo"),
    ("lightheaded", "Orthostatic hypotension"),
    ("feel faint", "Syncope/Orthostatic hypotension"),
    ("numbness", "Neuropathy"),
    ("tingling", "Neuropathy"),
    ("pins and needles", "Neuropathy"),
    ("confusion", "Neurological disorder/Infection/Meningitis"),
    ("can't think straight", "Neurological disorder"),
    ("confused", "Neurological disorder/Meningitis"),
    ("disoriented", "Neurological disorder/Infection"),
    ("seizure", "Epilepsy/Seizure disorder"),
    ("stroke", "Acute ischemic stroke"),
    ("weakness", "Neurological disorder/Stroke"),
    ("paralysis", "Stroke/Neurological disorder"),
    # GASTROINTESTINAL CONDITIONS - Patient language
    ("stomach pain", "Gastritis/GERD/IBS"),
    ("stomach ache", "Gastritis/GERD/IBS"),
    ("bad stomach pain", "Appendicitis/Gastritis"),
    ("stomach hurts", "Gastritis/GERD"),
    ("belly pain", "Gastritis/GERD/IBS"),
    ("belly ache", "Gastritis/GERD/IBS"),
    ("tummy pain", "Gastritis/GERD"),
    ("tummy hurts", "Gastritis/GERD"),
    ("gut pain", "Gastritis/IBS"),
    ("intestinal pain", "IBS/Gastritis"),
    ("severe stomach pain", "Appendicitis/Peritonitis"),
    ("severe abdominal pain", "Appendicitis/Peritonitis/Bowel obstruction"),
    ("sharp pain", "Appendicitis/Peritonitis"),
    ("cramping", "IBS/Menstrual cramps/Gastritis"),
    ("cramps", "IBS/Gastritis"),
    ("stomach upset", "Gastroenteritis/GERD"),
    ("upset stomach", "Gastroenteritis/GERD/Gastritis"),
    ("feel nauseous", "Gastroenteritis/GERD"),
    ("feeling sick", "Gastroenteritis/Viral infection"),
    ("gonna throw up", "Gastroenteritis/GERD"),
    ("throwing up", "Gastroenteritis"),
    ("vomiting", "Gastroenteritis/GERD"),
    ("can't keep food down", "Gastroenteritis"),
    ("diarrhea", "Gastroenteritis/IBS"),
    ("loose stool", "Gastroenteritis"),
    ("running to bathroom", "Gastroenteritis/IBS"),
    ("bloated", "IBS/Gastritis"),
    ("bloating", "IBS/Gastritis"),
    ("feel bloated", "IBS/Gastritis"),
    ("constipated", "Constipation/IBS"),
    ("constipation", "Constipation/IBS"),
    ("can't go", "Constipation"),
    ("indigestion", "GERD/Gastritis"),
    ("heartburn", "GERD/Gastritis"),
    ("reflux", "GERD"),
    ("acid reflux", "GERD"),
    # GENERAL/SYSTEMIC - Patient language
    ("fever", "Infection/Flu/Common cold"),
    ("high fever", "Serious infection/Meningitis"),
    ("temperature", "Fever/Infection"),
    ("feel hot", "Fever"),
    ("burning up", "Fever/Serious infection"),
    ("running a fever", "Fever/Infection"),
    ("chills", "Infection/Flu"),
    ("shaking chills", "Serious infection"),
    ("sweating", "Fever/Infection"),
    ("night sweats", "Tuberculosis/Infection"),
    ("tired", "Viral infection/Depression"),
    ("exhausted", "Viral infection/Serious illness"),
    ("fatigue", "Viral infection/Serious illness"),
    ("no energy", "Viral infection/Depression"),
    ("worn out", "Viral infection/Fatigue"),
    ("body aches", "Flu/Viral infection"),
    ("aching", "Flu/Muscle strain"),
    ("sore", "Viral infection/Flu"),
    ("everything hurts", "Flu/Serious infection"),
    ("lost appetite", "Viral infection/Serious illness"),
    ("can't eat", "Viral infection"),
    ("don't want to eat", "Viral infection/Depression"),
    ("weight loss", "Serious illness/Tuberculosis"),
    ("losing weight", "Serious illness/Cancer/TB"),
    ("not feeling well", "Viral infection"),
    ("under the weather", "Viral infection"),
    ("sick", "Viral infection/Illness"),
    ("infection", "Bacterial/Viral infection"),
    ("flu", "Influenza"),
    ("cold", "Common cold"),
    # MUSCULOSKELETAL CONDITIONS - Patient language
    ("broke my leg", "Fracture"),
    ("broke my arm", "Fracture"),
    ("broke", "Fracture"),
    ("break", "Fracture"),
    ("sprained ankle", "Ligament sprain"),
    ("sprain", "Ligament sprain"),
    ("twisted", "Ligament sprain/Musculoskeletal injury"),
    ("twisted ankle", "Ankle sprain"),
    ("strain", "Muscle strain"),
    ("pulled muscle", "Muscle strain"),
    ("joint swelling", "Joint injury/Arthritis"),
    ("swollen knee", "Knee injury"),
    ("knee swelling", "Knee injury"),
    ("knee pain", "Knee injury/Osteoarthritis"),
    ("my knee", "Knee injury"),
    ("back pain", "Back strain/Sciatica"),
    ("bad back", "Back strain/Sciatica"),
    ("lower back", "Back strain/Sciatica"),
    ("severe back pain", "Herniated disc/Sciatica"),
    ("can't move", "Severe musculoskeletal injury"),
    ("can't walk", "Severe injury/Fracture"),
    ("limping", "Injury/Pain"),
    ("neck pain", "Cervical strain/Whiplash"),
    ("shoulder pain", "Shoulder injury/Strain"),
    ("arm pain", "Nerve damage/Injury"),
    ("wrist pain", "Wrist injury/Carpal tunnel"),
    ("ankle pain", "Ankle injury"),
    ("arthritis", "Osteoarthritis/Rheumatoid arthritis"),
    ("joint pain", "Arthritis"),
    ("dislocation", "Joint dislocation"),
    # DERMATOLOGICAL CONDITIONS - Patient language
    ("rash", "Dermatitis/Eczema/Allergic reaction"),
    ("I have a rash", "Dermatitis/Eczema"),
    ("red rash", "Eczema/Dermatitis/Rosacea"),
    ("severe rash", "Allergic reaction/Eczema"),
    ("breaking out", "Eczema/Dermatitis/Acne"),
    ("itching", "Eczema/Scabies/Allergic reaction"),
    ("itchy", "Eczema/Allergic reaction"),
    ("itching rash", "Eczema/Allergic reaction"),
    ("blistering", "Herpes zoster/Chickenpox"),
    ("blisters", "Herpes zoster/Chickenpox"),
    ("hives", "Allergic reaction"),
    ("swelling", "Allergic reaction/Infection"),
    ("skin issues", "Dermatological condition"),
    ("acne", "Acne vulgaris"),
    ("psoriasis", "Psoriasis"),
    ("eczema", "Eczema"),
    # PSYCHIATRIC/EMOTIONAL - Patient language
    ("panic attack", "Panic disorder"),
    ("panic", "Panic disorder"),
    ("freaking out", "Panic disorder/Anxiety"),
    ("losing it", "Anxiety/Panic disorder"),
    ("meltdown", "Anxiety/Emotional distress"),
    ("anxious", "Anxiety disorder"),
    ("anxiety", "Anxiety disorder"),
    ("worried", "Anxiety disorder"),
    ("worry", "Anxiety disorder"),
    ("can't calm down", "Anxiety disorder"),
    ("overwhelmed", "Anxiety/Stress"),
    ("stressed", "Stress/Anxiety"),
    ("depressed", "Major depressive disorder"),
    ("depression", "Major depressive disorder"),
    ("feeling down", "Major depressive disorder"),
    ("sad all the time", "Major depressive disorder"),
    ("no motivation", "Major depressive disorder"),
    ("suicidal", "Suicidal ideation/Depression"),
    ("want to hurt myself", "Suicidal ideation"),
    ("hopeless", "Major depressive disorder"),
    # ALLERGIES - Patient language
    ("allergic reaction", "Allergic reaction"),
    ("allergic", "Allergic reaction"),
    ("allergy", "Allergic reaction"),
    ("swelling face", "Allergic reaction/Angioedema"),
    ("tongue swelling", "Anaphylaxis/Allergic reaction"),
    ("can't swallow", "Anaphylaxis/Throat swelling"),
    ("throat closing", "Anaphylaxis"),
    ("anaphylaxis", "Anaphylactic shock"),
    # OTHER CONDITIONS - Patient language
    ("kidney pain", "Kidney disease/Nephrolithiasis"),
    ("kidney stone", "Kidney stone"),
    ("liver pain", "Liver disease"),
    ("liver", "Liver disease"),
    ("poison", "Poisoning/Toxin exposure"),
    ("overdose", "Drug overdose"),
    ("too much", "Overdose/Poisoning"),
    ("bleeding", "Hemorrhage/Bleeding disorder"),
    ("bleeding a lot", "Hemorrhage"),
    ("won't stop bleeding", "Hemorrhagic shock"),
    ("bruising", "Bleeding disorder/Trauma"),
]
